@startuml

skinparam monochrome true

 title Universal protocol: DEV1 <---> DEV2 (RX buffer overflow)

DEV1 -> DEV2: Header + payload + tail + CRC
note over DEV2: Response (RX buffer overflow)
DEV2 -> DEV1: BUFFER OVERFLOW
note left: Problem is reported\nto higher layer


@enduml