@startuml

skinparam monochrome true

 title Bridge: PC_app <--> AVR - get setting (invalid device ID)

participant PC_app 
box "AVR"
    participant Uniprot
    participant Bridge
    participant HW
    participant DEV_X_driver
end box




PC_app -> Uniprot: Command\n"Get setting of command Y\n from device X"
activate PC_app

activate Uniprot
Uniprot -> Bridge: Command\n"Get setting of command Y\n from device X"
activate Bridge

Bridge -> HW: Get setting of command Y\n from device X
activate HW
note over HW: Device ID not X exist


HW -> Bridge: Result code
deactivate HW
Bridge -> Uniprot: Result code
deactivate Bridge

Uniprot -> PC_app: Result code
deactivate Uniprot

deactivate PC_app
@enduml