@startuml

skinparam monochrome true

 title Bridge: PC_app <--> AVR - get metadata (success)

participant PC_app 
box "AVR"
    participant Uniprot
    participant Bridge
    participant HW
    participant DEV_X_driver
end box




PC_app -> Uniprot: Command "Get metadata from device X"
activate PC_app

activate Uniprot
Uniprot -> Bridge: Command "Get metadata from device X"
activate Bridge

Bridge -> HW: Get metadata from device X
activate HW
note over HW: Device ID X exist


HW -> DEV_X_driver: Get metadata
activate DEV_X_driver

DEV_X_driver -> HW: Pointer to metadata
deactivate DEV_X_driver

HW -> Bridge: Load metadata
deactivate HW
Bridge -> Uniprot: Result code + metadata
deactivate Bridge

Uniprot -> PC_app: Result code + metadata
deactivate Uniprot

deactivate PC_app
@enduml