@startuml

skinparam monochrome true

 title Bridge: PC_app <--> AVR - set settings (invalid command)

participant PC_app 
box "AVR"
    participant Uniprot
    participant Bridge
    participant HW
    participant DEV_X_driver
end box




PC_app -> Uniprot: Command\n"Set settings of command Y\n to device X + value (4B)"
activate PC_app

activate Uniprot
Uniprot -> Bridge: Command\n"Set settings of command Y\n to device X + value (4B)"
activate Bridge

Bridge -> HW: Set settings of command Y\n to device X + value (4B)
activate HW
note over HW: Device ID X exist


HW -> DEV_X_driver: Set settings of command Y + value
activate DEV_X_driver
note over DEV_X_driver: Command Y not exist
 

DEV_X_driver -> HW: Result code
note right: Return 0 if SUCCESS
deactivate DEV_X_driver

HW -> Bridge: Result code
deactivate HW
Bridge -> Uniprot: Result code
deactivate Bridge

Uniprot -> PC_app: Result code
deactivate Uniprot

deactivate PC_app
@enduml